version: '3'

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '8081:81'
    volumes:
      - ./nginxproxymanager:/data
      - ./letsencrypt:/etc/letsencrypt
    extra_hosts:
      - host.docker.internal:host-gateway