version: '3'

services:
  edgely:
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@pgbouncer:5432/edgely?schema=public
    container_name: edgely-prod
    command: yarn start
    depends_on:
      - "postgres"

  postgres:
    image: postgres:15-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgbouncer:
    image: edoburu/pgbouncer
    expose:
      - 5432
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=postgres
       - DB_HOST=postgres
       - DB_NAME=edgely
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres
       - PGBOUNCER_AUTH_TYPE=md5
    ports:
      - "127.0.0.1:5432:5432"
    depends_on:
      - postgres

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '127.0.0.1:81:81' # Admin Web Port
    volumes:
      - ./nginxproxymanager:/data
      - ./letsencrypt:/etc/letsencrypt